languageCode = "en-us"
author       = "John Koelndorfer"
title        = "John Koelndorfer"
theme        = "johnk-io"

relativeURLs = false
uglyURLs     = true

PygmentsUseClasses = true
PygmentsCodeFences = true

[params]
author      = "John Koelndorfer"
intro       = "Technologist and purveyor of fine automation"
description = "Site Reliability Engineer @ [AerisWeather](https://www.aerisweather.com)"
dateformat  = "2006-01-02"
authorimage = "personalphoto.jpg"

[params.meta]
description = "The personal website of John Koelndorfer."
keywords    = "Koelndorfer, Technology, DevOps, Software, Engineering, Blog"

[params.social]
blog     = "/blog.html"
github   = "https://www.github.com/jkoelndorfer"
linkedin = "https://www.linkedin.com/in/jkoelndorfer"
email    = "john@johnk.io"

[[menu.main]]
name       = "blog"
weight     = "100"
identifier = "blog"
url        = "/blog.html"
