#!/bin/bash

set -eo pipefail

env=$1

static_object_cache_max_age=604800

function usage() {
    echo 'You must pass the name of the environment as the first argument to this script.' >&2
    echo 'Valid values are: dev, prod' >&2
}

function set_cache_control_max_age() {
    local path=$1

    aws s3 cp \
        --acl public-read \
        --recursive \
        --cache-control "max-age=$static_object_cache_max_age" \
        "$path" "$path"
}

if [[ "$env" == 'prod' ]]; then
    base_url='https://www.johnk.io'
elif [[ "$env" == 'dev' ]]; then
    base_url='https://www.dev.johnk.io'
else
    usage
    exit 1
fi

script_dir=$(dirname "$(realpath "$0")")
aws_account_id=$(aws sts get-caller-identity --query 'Account' --output text)

cd "$script_dir"
rm -rf 'public/'
hugo --baseURL "$base_url"
cd public

s3_base_path="s3://$aws_account_id-blog-$env"
aws s3 sync --acl public-read --delete . "$s3_base_path"
set_cache_control_max_age "$s3_base_path/fonts/"
